### ISSUE TITLE
Usage outside IBM Bluemix environment

### ISSUE THREAD

**Issue by hassen2017** [ibm-watson-iot/node-red-contrib-scx-ibmiotapp#3]
Hi,

Im trying to use Ibmiot in my localhost ( http://127.0.0.1:1880/) but i can't access to authentification and API Key and API Token options are not available  ..

so please how can i resolve this issues ?

**Comment by hassen2017** [comment]
More informations :  
 
I had create  “Internet of Things Platform Starter” service in bluemix then i was working with Node-Red in bluemix to visualising data into node-red-dashboard and it's worked fine for me  ..but when i was trying to doing the same work in my localhost i couldn't becausee there is not any authentication to edit in "IBMIOT in" node ..

Is there any other solution to costumize my dashboard in bluemix or in my local ??

**Comment by amprasanna** [comment]
@hassen2017 - When you say, you don't get to see 'any authentication to edit in IBMIoT In node', I'm assuming that the Authentication option is currently set to Quickstart and not to API Key. I am attaching a snapshot of the IBM IoT In node, showcasing Authentication options. If you have deployed on Bluemix, then by default, the Watson IoT Platform (WIoTP) service is binded to your application and thus, the application can directly leverage the IoTP credentials. 

However, on a local setup, you should ensure that you choose the API Key authentication mechanism and then provide the API Key and it's respective API Token.

![choose_api_key_authentication](https://cloud.githubusercontent.com/assets/13063619/26778573/78373980-49ff-11e7-8686-9b7405e0f7e4.PNG)

Let me know, if my understanding of your issue correct. Else, please share snapshot(s) to further explain your issue.
